---
title: "Reading List"
---

| Week | Title                                                                              | Item Link                                                                              | Note for Student                                                                      |
|------|------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------|
| 1    | Conducting research in psychology: measuring the weight of smoke                   | [link](https://resourcelists.lib.deakin.edu.au/items/6D5F19BD-4761-1CD7-E509-032722AE3A8D.html) | Chapter 1 pp. 1-28  -- NOTE: Print Text Only                                          |
| 1    | The scientist practitioner: research and accountability in the age of managed care | [link](https://resourcelists.lib.deakin.edu.au/items/E58AF5B9-E827-AB80-46A4-B1889F74884B.html) | Print Text Only                                                                       |
| 2    | Conducting research in psychology: measuring the weight of smoke                   | [link](https://resourcelists.lib.deakin.edu.au/items/8FA6FA93-E0A2-B22B-30D5-DB8B9CE857FF.html) | Chapter 2 pp. 29-57 (i.e., excluding the section on ethics)  -- NOTE: Print Text Only |
| 2    | Theories and explanations                                                          | [link](https://resourcelists.lib.deakin.edu.au/items/341E55C0-F4FE-97D7-D239-F30DFF7C3926.html) |                                                                                       |
| 3    | Conducting research in psychology: measuring the weight of smoke                   | [link](https://resourcelists.lib.deakin.edu.au/items/BFDDFB59-2CE5-A75F-817E-B01C7507910E.html) | Chapter 3 pp. 69-88  -- NOTE: Print Text Only                                         |
| 4    | Conducting research in psychology: measuring the weight of smoke                   | [link](https://resourcelists.lib.deakin.edu.au/items/006735C3-624E-021B-C913-047DFCD52422.html) | Chapter 5 pp. 128-161  -- -- NOTE: Print Text Only                                    |
| 5    | Conducting research in psychology: measuring the weight of smoke                   | [link](https://resourcelists.lib.deakin.edu.au/items/EBFB7ED2-94E6-C6EC-9400-B69763D42F7F.html) | Chapter 7 pp. 198-231 & Chapter 8 pp. 240-255 ---- NOTE: Print Text Only              |
| 6    | Conducting research in psychology: measuring the weight of smoke                   | [link](https://resourcelists.lib.deakin.edu.au/items/4834D43B-B8B3-E358-3490-848E0B6F3F0D.html) | Chapter 6 pp. 162-197 ---- NOTE: Print Text Only                                      |
| 7    | An introduction to qualitative research                                            | [link](https://resourcelists.lib.deakin.edu.au/items/D65B14A0-A973-C438-4C27-1731FEE5191D.html) |                                                                                       |
| 7    | Approaches to social research                                                      | [link](https://resourcelists.lib.deakin.edu.au/items/75623BB0-C79C-E5B3-4AC9-B498FAF186E9.html) |                                                                                       |
| 7    | Conducting research in psychology: measuring the weight of smoke                   | [link](https://resourcelists.lib.deakin.edu.au/items/3F0A3EBA-C013-A82E-2597-B6CA02D05793.html) | Chapter 2, pp. 20-27 ---- NOTE: Print Text Only                                       |
| 7    | Using thematic analysis in psychology                                              | [link](https://resourcelists.lib.deakin.edu.au/items/A1699500-F857-D28D-B2F3-C72E153044E5.html) |                                                                                       |
| 8    | Conducting research in psychology: measuring the weight of smoke                   | [link](https://resourcelists.lib.deakin.edu.au/items/9BB1EABF-D5CF-6CDC-E994-E64AD6B65303.html) | Chapter 2, pp. 61-66 ---- NOTE: Print Text Only                                       |
| 8    | Foundations of ethical behavior                                                    | [link](https://resourcelists.lib.deakin.edu.au/items/58B40E90-30F0-8FE5-75C1-80436E383A8E.html) |                                                                                       |
| 8    | Ethical fading: the role of self-deception in unethical behavior                   | [link](https://resourcelists.lib.deakin.edu.au/items/D8C2EB6E-42FD-1D36-13EC-A06409EF991B.html) |                                                                                       |
| 8    | NHMRC's National Statement on Ethical Conduct in Human Research                    | [link](https://resourcelists.lib.deakin.edu.au/items/E309795A-E6EB-6660-72C9-ADFB974F6F7B.html) |                                                                                       |
| 9    | Conducting research in psychology: measuring the weight of smoke                   | [link](https://resourcelists.lib.deakin.edu.au/items/5CECC4BA-CAFE-643E-B297-B3B34E2D539D.html) | Chapter 4, pp. 89-121 ---- NOTE: Print Text Only                                      |
| 10   | Conducting research in psychology: measuring the weight of smoke                   | [link](https://resourcelists.lib.deakin.edu.au/items/63B3A83A-C9A2-6A76-DF0D-CB002ED11BFC.html) | Chapter 9, pp. 274-292 -- -- NOTE: Print Text Only                                    |
| 11   | Extracts from Statistics for the behavioral sciences                               | [link](https://resourcelists.lib.deakin.edu.au/items/E3C266C3-5732-2CD0-A967-DE5E986529FC.html) |                                                                                       |